[package]
name = "fluxus"
version = "0.1.0"
authors = ["cyprien"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.1", features = ["router"] }
dioxus-i18n = "0.5.0"

[features]
default = ["mobile"]
#web = ["dioxus/web"]
#desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
